// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/developer-portfolio/Portfolio.tsx": () => import("../components/mockups/developer-portfolio/Portfolio.tsx")
};
